### ISSUE TITLE
Assign

### ISSUE THREAD

**Issue by simplesmiler** [mariocasciaro/object-path-immutable#1]
A method similar to `Object.assign` would be lovely.

``` js
var state = {
  '0': {
    info: { ... },
    comments: [ ... ],
  },
  ...,
};

var data = { info: ... }; // @NOTE: comes from the action, may contain different fields
state = immutable.assign(state, [id], data); // @NOTE: id comes from the action
```

With the current api this is very verbose and unchainable:
``` js
state = Object.keys(data).reduce(function(state, key) {
  return immutable.set(state, [id, key], data[key]);
}, state);
```

**Comment by simplesmiler** [comment]
Well I guess it can also be done like this:
``` js
state = immutable.set(state, [id], Object.assign({}, state[id], data));
```

But having a native method would be superior.

**Comment by mariocasciaro** [comment]
I see your point and yes, I think we need such functionality. It's like merging an object without mutating the existing one. If I understand it correctly, with the new functionality, your example could be generalized to something like this:
```
state = immutable.merge(state, {'0': data})
```

**Comment by simplesmiler** [comment]
Similar, but not quite. `Object.assign` does a shallow merge, not a deep merge, that is:

``` js
var a = { shallow: 0, keep: 0, deep: { one: 0, two: 0 } };
Object.assign(a, { shallow: 1, deep: { one: 1 } });
console.log(a); // { shallow: 1, keep: 0, deep: { one: 1 } }
// while deep merge would give { shallow: 1, keep: 0, deep: { one: 1, two: 0 } }
```

Deep merge, being useful sometimes, might be complicated and ambiguous, while shallow merge is fast and has a well-defined semantics.

**Comment by mariocasciaro** [comment]
OK, makes sense. Let's move this forward then, let's promote this to a feature. Any PR is welcome, otherwise I'll look into as soon as I have some time.

**Comment by simplesmiler** [comment]
Made a PR.

**Comment by mariocasciaro** [comment]
Thanks! Merged

**Comment by simplesmiler** [comment]
Cool beans, using it in the redux app I'm working on.
