### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by andreyan-andreev** [mariocasciaro/object-path-immutable#11]
Is it possible to include typescript definitions?

**Comment by mariocasciaro** [comment]
I don't use typescript, but if someone submits a PR I'll gladly merge it.

**Comment by ryanlaws** [comment]
@syabro should the definitions file perhaps be named index.d.ts? I don't use TypeScript regularly so I can't speak much to tooling for real TypeScript users, but Visual Studio Code isn't picking up the definitions with the current filename. When I rename it within node_modules (not a real solution, of course), it works.

**Comment by syabro** [comment]
@rainydio have no idea :) works for my IDEA, but of course you may add a PR with renaming I bet it will break anything

**Comment by mariocasciaro** [comment]
#29 should fix this. Closing.
