### ISSUE TITLE
Set root object

### ISSUE THREAD

**Issue by sunny-lan** [mariocasciaro/object-path-immutable#18]
Why does this not work:

```
immutable.set(this.state, [], {test:'vcvcx'});
```

**Comment by mariocasciaro** [comment]
Because in JS we cannot pass a reference to a variable

**Comment by sunny-lan** [comment]
Is it possible to change the library so it returns the new reference to the object (and returns the same reference if the object reference hasn't changed)?

So you could use it like this:

```js
this.state = immutable.set(this.state, [], {test:'vcvcx'});
```

**Comment by mariocasciaro** [comment]
Sorry, I see your point now. Yes, that would actually be possible. PRs welcome ;)

**Comment by sunny-lan** [comment]
Alright, I'll work on that. Just a question, objects not on the path of the update/set aren't cloned right?

For example:

```js
let k = {
  a:[1,2],
  b:3
}
let j=immutable.set(k, ['b'], 4);
```

Would that leave `j.a === k.a`?

**Comment by mariocasciaro** [comment]
That's correct
