### ISSUE TITLE
Delete multiple path with a single .del call.

### ISSUE THREAD

**Issue by popo63301** [mariocasciaro/object-path-immutable#22]
I'd like to suggest you a feature. Why not deleting multiple paths (referred in a single array) within  a single .del call.

For instance, we have this obj: 
```
const obj = {
  a: {
    b: 'c',
    c: ['d', 'f']
  }
}
```

And by calling the new del function, we will have: 
```
const newObj = immutable.del(obj, ['a.c.0', 'a.b' ])
// {
//   a: {
//     c: ['f']
//   }
// }
```

I may try to implement it myself if I have time.

**Comment by mariocasciaro** [comment]
This can be easily achieved with something like :
```
const newObj = ['a.c.0', 'a.b' ].reduce((oj, p) => o.del(p), obj)
```

(warning: untested code)
