### ISSUE TITLE
enhancement: support escaped dots as single property

### ISSUE THREAD

**Issue by ilovett** [mariocasciaro/object-path-immutable#23]
`immutable(state).set('nest.nest.nest.192\.168\.1\.0.details', blah)`

In this example there would be a property `192.168.1.0` instead of nested `192` -> `168` -> `1` -> `0`

**Comment by mariocasciaro** [comment]
This sounds like a very nice idea. Looking for volunteers for implementing this.

**Comment by ilovett** [comment]
I ended up working around this by using an array `['nest', 'nest', '192.168.1.0', 'details']`
