### ISSUE TITLE
Typo in README example

### ISSUE THREAD

**Issue by OzTK** [mariocasciaro/object-path-immutable#28]
From this section: https://github.com/mariocasciaro/object-path-immutable#set-initialobject-path-value

It seems this example doesn't work:

```js
const newObj3 = immutable.set(obj, ['a', 'b'], v => 'f')
```
Doesn't `set` take a value only and not an updater?

**Comment by mariocasciaro** [comment]
Yes, that's correct, it's indeed a typo. Thanks for reporting

**Comment by mariocasciaro** [comment]
It's fixed now
