### ISSUE TITLE
add getter methods

### ISSUE THREAD

**Issue by LabiKyo** [mariocasciaro/object-path-immutable#3]
I wonder why getter methods are not included. I'd like to use this module just like `object-path`, not requiring both.

**Comment by mariocasciaro** [comment]
I think there's no point in duplicating the `object-path` functionality here, what's your concern regarding requiring and using `object-path` in combination with `object-path-immutable`?

PS: In the future we might split the two libraries into one library-per-function like lodash is doing

**Comment by LabiKyo** [comment]
Just like what you do in the example, I want to have a global ObjectPath or Immutable helper. For now I have to required both and merge them manually, which is weird from my point of view.

**Comment by neekey** [comment]
need a getter +1

**Comment by neekey** [comment]
the same reason with @LabiKyo , for now, I need to install two modules like:

```js
import objectPathImmutable from 'object-path-immutable';
import objectPath from 'object-path';

const state = { ... };

// use one module to set
objectPathImmutable.set(state, [], ..);

// use another to get...
objectPath.get(state, []);
```

It just feels more intact if the module can provide both `set` and `get`...

**Comment by LabiKyo** [comment]
@neekey You may want to try `lodash`'s `get`/`set` or `react-addons-update`.

**Comment by neekey** [comment]
@labikyo thanks, looks like lodash's get is another option, but I still need this module, since lodash's set function mutate objects and I also need to do something like push and delete.

react-addins-update is also an option, but I don't like the MongoDB style syntax, and also it does not provide the command to delete I think.

For the moment this module kind of the best I can find

**Comment by LabiKyo** [comment]
@neekey just use `lodash/fp`, it's immutable. lodash is good for get/set one deep prop while update is good for batch update, i use them both.

**Comment by laurentvd** [comment]
I was - at first - confused. I built something using object-path and then 'switched' to object-path-immutable. This issue thread cleared it up and I understand the reasoning behind it now. However, it feels as if I have two `set` functions loaded in my app; the regular and the immutable one. Maybe the underscore model is indeed a solution for this, but in the meantime, maybe make explicit in the immutable docs that you need the object-path package for getting stuff.

**Comment by mariocasciaro** [comment]
Ok. since there is so much demand, I will start considering this as a feature request 😉

**Comment by laurentvd** [comment]
👍

**Comment by dobryanskyy** [comment]
Indeed, adding a get function would be quite useful.

**Comment by iChip** [comment]
I picked this library because I don't want a mutable path library in my project. Forcing consumers to use both libraries seems pretty backwards.

**Comment by josdejong** [comment]
A get function would be very useful for me too!

**Comment by 11111000000** [comment]
+1
