### ISSUE TITLE
Typescript definitions incorrectly list default export 

### ISSUE THREAD

**Issue by craigambrose** [mariocasciaro/object-path-immutable#35]
This package doesn't actually have a default export. Instead it exports each function explicitly. That's fine and good, and means you can do something like:

```js
import { set } from "object-path-immutable"

set(originalObject, "some.path", "value")
```

However, the typescript definition lists a single default export only which implies that people will only use:

```js
import immutable from "object-path-immutable"

immutable.set(originalObject, "some.path", "value")
```

Aside from being a bit more verbose, this isn't actually what the package exports. It might work with typescript's optional "allowSyntheticDefaultImports" setting, but I find that this doesn't work in all situations. I think it'd be better if the typescript definition matched the actual package export, which is that each function is exported separately.

**Comment by ulrichb** [comment]
Since v 4.0 and the addition of `"module": "esm/object-path-immutable.js"` in [package.json](https://github.com/mariocasciaro/object-path-immutable/commit/3ba5214cdb132297f405b51013676b4e10d38437#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) this doesn't work at all (even with `--esModuleInterop`).

Please change the TypeScript definition to

```ts
declare module 'object-path-immutable' {
    export function wrap<T>(obj: T): WrappedObject<T>;
    export function set<T = object>(src: T, path?: Path, value?: any) : T;
    // ...
}
```

**Comment by mariocasciaro** [comment]
Fixed in 4.0.2

**Comment by ulrichb** [comment]
Thanks @mariocasciaro!

**Comment by tyson-kubota** [comment]
We got bitten by this on an upgrade from 3.x to 4.x. 

Should probably note the desired import syntax in https://github.com/mariocasciaro/object-path-immutable#api . I'll open a PR.
