### ISSUE TITLE
Support for immutable transactions

### ISSUE THREAD

**Issue by lawnsea** [mariocasciaro/object-path-immutable#5]
Thanks for the awesome and super useful library.

We recently ran into a performance issue that we root-caused to performing a large number of immutable operations during the same turn of the event loop. When we benchmarked, we found that performing N immutable operations is O(N^2).

Our solution was to [implement a module](https://github.com/RetailMeNotSandbox/redux-mount-store/pull/9) that supports the object-path-immutable API, but as a transaction from one object to another - without creating intermediate copies. We saw a sizable performance win as a result (see the benchmark in the linked PR).

Would y'all be interested in landing this work into your library? If so, I'll refactor the module to use your internal API and open a PR.

**Comment by mariocasciaro** [comment]
This sounds great, I actually was already aware of the issue, but never had the time to work on it, so the PR is very welcome. The natural place to implement your transaction logic is in the 'chain-mode' function where you can queue all the operations and then run them in batch when value() is invoked. How does that sound?

**Comment by lawnsea** [comment]
Great! I was thinking that would be the right place to integrate transactions as well.

I did a close reading of the code today at lunch and have a rough plan. This will touch some pretty fundamental parts of the existing code, though, so I'm going to spend some time pushing the test coverage closer to 100% first.

**Comment by dacz** [comment]
@lawnsea 👍

**Comment by cappslock** [comment]
Could this be published?

**Comment by mariocasciaro** [comment]
This should already be published in 0.5.0

**Comment by mariocasciaro** [comment]
I probably just forgot to push the new version update to GitHub but the new code is already on npm.

**Comment by cappslock** [comment]
Great! Yeah, I did not see it on master so I didn't think it was published, but I see it as a tag now (and it's published to npm).
