### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by lawnsea** [mariocasciaro/object-path-immutable#7]
I'm working on #5 and one thing that's tricky is the inconsistent code style (semicolons on some lines and not on others, etc.).

I think it would be helpful to pick a style guide and go with it. I'm happy to fix all the style bugs. What style should we use?

**Comment by mariocasciaro** [comment]
Thanks for noticing that, I really haven't paid much attention to it :).
I'll be happy if we use feross/standard

**Comment by lawnsea** [comment]
Cool. I'll make that happen in a separate PR.

**Comment by mariocasciaro** [comment]
I think this has been fixed with #10
